name: Standalone

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

defaults:
  run:
    shell: bash

jobs:
  standalone:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 20
    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v4
      - name: Set up Python ğŸ ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        timeout-minutes: 20
        run: |
          pip install -e . -U -r requirements/_tests.txt \
            -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip --version
          pip list

      - name: Run standalone script
        run: bash ./scripts/run_standalone_tests.sh "tests"
        env:
          COVERAGE_SOURCE: "lightning_utilities"
